#!/usr/bin/env python3

import configparser
import os

from jira import JiraHook, JiraLogin, JiraLogout, JiraAddComment

config = configparser.ConfigParser()

config.read(os.path.expanduser('~/gerrit_hook.config'))
jira_config = config['jira']

jira_hook = JiraHook(jira_config['url'])
jira_hook.appendJiraCommand(command=JiraLogin(jira_config['username'], jira_config['password']))
jira_hook.appendJiraCommand(command=JiraAddComment('TEST-1', 'This is a test'))
jira_hook.appendJiraCommand(command=JiraLogout())
jira_hook.execute()
